import { PermissionKey, PERMISSIONS } from './permissions';

export type UserRole = 
  | 'customer'
  | 'seller'
  | 'rider'
  | 'admin';

/**
 * Enterprise role-to-permission mapping matrices
 */
export const ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  customer: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.SHOPS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.REVIEWS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
  ],
  
  seller: [
    PERMISSIONS.SHOPS_VIEW,
    PERMISSIONS.SHOPS_MANAGE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.REVIEWS_VIEW,
    PERMISSIONS.REVIEWS_REPLY,
    PERMISSIONS.COUPONS_VIEW,
    PERMISSIONS.COUPONS_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.WALLET_MANAGE,
    PERMISSIONS.PAYOUTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_REPLY,
  ],
  
  rider: [
    PERMISSIONS.DELIVERIES_VIEW,
    PERMISSIONS.DELIVERIES_UPDATE,
    PERMISSIONS.DELIVERIES_PROOF,
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
  ],

  admin: Object.values(PERMISSIONS) as PermissionKey[],
};
